import { type NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {

  const [gameNumber,setGameNumber] = useState(1);
  const [useAlternateCardSet, setUseAlternateCardSet] = useState(false);

  return (
    <>
      <Head>
        <title>Dragon's Maze Game Select</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#3A4A41] to-[#455148]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl drop-shadow-m font-extrabold tracking-tight text-amber-400 sm:text-[5rem]">
            Dragon's Maze
          </h1>
          <div className="gap-2">
            <form className="flex flex-col items-center justify-center">
            <label htmlFor="lobby-number" className="text-3xl text-white ps-10 p-2.5">Lobby Number:</label>
              <input id='lobby-number' type='number' className="bg-emerald-600 border text-white text-sm rounded-lg focus:ring-orange-100 focus:border-orange-200 block w-full ps-10 p-2.5" placeholder='Lobby Number:' min={1} value={gameNumber} onChange={e => setGameNumber(Number.parseInt(e.target.value))}></input>
              {/* <p className='text-white'>Use Alternate Card Set <input type='checkbox' id='cardset' checked={useAlternateCardSet} onChange={()=>setUseAlternateCardSet(!useAlternateCardSet)}/></p> */}
              <Link href={{pathname: `/game/${gameNumber}`, query: {cardset:useAlternateCardSet}}} className="pt-6"><button className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20">Start Playing!</button></Link>
            </form>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
